### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by DeepChoudhuri** [CPMD-code/CPMD#1]
Used a modified LINUX-X86_64-GFORTRAN-MPI (see below)
#INFO#
#INFO# Configuration to build a serial cpmd executable for a linux pc using 
#INFO# the GNU Fortran compiler.
#INFO#
#INFO# V. Weber
#INFO#

     IRAT=2
     FC='mpif90'
     CC='gcc'
     LD='mpif90'
     CPP=''
     CPPFLAGS='-D__Linux -D__GNU -D__PARALLEL -D__HAS_FFT_DEFAULT    '
     FFLAGS_GROMOS='-ffixed-form $(FFLAGS)' 
     FFLAGS_GROMOS_MODULES=' $(FFLAGS)' 
     AR='/usr/bin/ar ruv'
     RANLIB='/usr/bin/ranlib'
     if [ $debug ]; then
       FFLAGS='-g -O0 -fcheck=all -Wuninitialized -Wall'
       CFLAGS='-g -O0 -Wall'
     else
       FFLAGS='-O2 -Wall'
       CFLAGS='-O2 -Wall'
     fi
     if [ $omp ]; then
       FFLAGS=${FFLAGS}' -fopenmp'
       OMP3_DISABLED=`{ ${FC} -v; } 2>&1 | ${GREP} version | ${AWK} '{ print ( $3 < "4.7.0" ) ? "true" : "false" }'`
       LIBS='/Users/deep/myLibs/scalapack-2.2.1/lib/libscalapack.a /Users/deep/myLibs/openblas-0.3.21/lib/libopenblas.a'
     else
       LIBS='/Users/deep/myLibs/scalapack-2.2.1/lib/libscalapack.a /Users/deep/myLibs/openblas-0.3.21/lib/libopenblas.a'
     fi
     LFLAGS=' '${LIBS}
     if [ $coverage ]; then
       FFLAGS=${FFLAGS}' --coverage'
       LFLAGS='--coverage '${LFLAGS}
     fi

Primary ERROR:

/Users/deep/SOFTWARE/CPMD/src/dotp_utils.mod.F90:96:37:

   51 |        dotp=dotp+2.0_real_8*ddot(2*n-2,a(2),1,b(2),1)
      |                                       2
......
   96 |      dotp=dotp+2.0_real_8*ddot(2*n-2,a(3),1,b(3),1)
      |                                     1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/COMPLEX(8)).
/Users/deep/SOFTWARE/CPMD/src/dotp_utils.mod.F90:96:44:

   51 |        dotp=dotp+2.0_real_8*ddot(2*n-2,a(2),1,b(2),1)
      |                                              2
......
   96 |      dotp=dotp+2.0_real_8*ddot(2*n-2,a(3),1,b(3),1)
      |                                            1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/COMPLEX(8)).
make[1]: *** [dotp_utils.mod.o] Error 1
make: *** [default,] Error 2

**Comment by foeroyingur** [comment]
For GCC >= 10.0, you need to add "-fallow-argument-mismatch" to FFLAGS

**Comment by DeepChoudhuri** [comment]
Thank you for the response!  Seems like LINUX-X86_64-GFORTRAN-MPI does not work on my M1 apple.  Using the same suggested FFLAG I was able to go pretty far with "MACOSX-GFORTRAN-INTEL-MPI" (see below .. but with some errors)

#INFO#
#INFO# Configuration to build a serial cpmd executable for a linux pc using 
#INFO# the GNU Fortran compiler.
#INFO# contributed by R Vuilleumier <vuilleum@lptl.jussieu.fr>
#INFO# debug version by T Laino <teo@zurich.ibm.com>

     IRAT=2
     FC='mpif90'
     CC='mpicc'
     LD='mpif90'
     CPP=''
     CPPFLAGS='-D__Linux  -D__HAS_FFT_DEFAULT  \
           -D__PARALLEL '
     FFLAGS_GROMOS='-ffixed-form  $(FFLAGS)' 
     FFLAGS_GROMOS_MODULES=' $(FFLAGS)' 
     if [ $debug ]; then
       FFLAGS='-g -O0 -fbounds-check -Wuninitialized'
       CFLAGS='-g -O0  -m32 -Wall'
     else
       FFLAGS='-O2 -fallow-argument-mismatch'
       CFLAGS='-O2  -m32 -Wall'
     fi
     if [ $omp ]; then
       echo "OMP settings not available!"
       exit 1
       LIBS='-Wl,-framework -Wl,Accelerate -Wl,-Y -Wl,10'
     else
       LIBS='-Wl,-framework -Wl,Accelerate -Wl,-Y -Wl,10'
     fi
     LFLAGS=' '${LIBS}
     if [ $coverage ]; then
       FFLAGS=${FFLAGS}' --coverage'
       LFLAGS='--coverage '${LFLAGS}
     fi

ERRO message (can you please help):

ar: creating archive /Users/deep/SOFTWARE/CPMD/build/lib/libcpmd.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: archive member: /Users/deep/SOFTWARE/CPMD/build/lib/libcpmd.a(sysdepend.o) cputype (12) does not match previous archive members cputype (16777228) (all members must match)
/Library/Developer/CommandLineTools/usr/bin/ranlib: archive member: /Users/deep/SOFTWARE/CPMD/build/lib/libcpmd.a(c_mem_utils.o) cputype (12) does not match previous archive members cputype (16777228) (all members must match)
ranlib /Users/deep/SOFTWARE/CPMD/build/lib/libcpmd.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: archive member: /Users/deep/SOFTWARE/CPMD/build/lib/libcpmd.a(sysdepend.o) cputype (12) does not match previous archive members cputype (16777228) (all members must match)
/Library/Developer/CommandLineTools/usr/bin/ranlib: archive member: /Users/deep/SOFTWARE/CPMD/build/lib/libcpmd.a(c_mem_utils.o) cputype (12) does not match previous archive members cputype (16777228) (all members must match)
make[1]: *** [/Users/deep/SOFTWARE/CPMD/build/lib/libcpmd.a] Error 1
make: *** [default,] Error 2

**Comment by DeepChoudhuri** [comment]
Finally success !! Am pasting the configuration contents below - this works for Apple M1 laptops.

Configuration :
---------------
#INFO#
#INFO# Configuration to build a serial cpmd executable for a linux pc using 
#INFO# the GNU Fortran compiler.
#INFO# contributed by R Vuilleumier <vuilleum@lptl.jussieu.fr>
#INFO# debug version by T Laino <teo@zurich.ibm.com>

     IRAT=2
     FC='mpif90'
     CC='gcc'
     LD='mpif90'
     CPP=''
     CPPFLAGS='-D__Linux  -D__HAS_FFT_DEFAULT  \
           -D__PARALLEL '
     FFLAGS_GROMOS='-ffixed-form  $(FFLAGS)' 
     FFLAGS_GROMOS_MODULES=' $(FFLAGS)' 
     if [ $debug ]; then
       FFLAGS='-g -O0 -fbounds-check -Wuninitialized'
       CFLAGS='-g -O0 -Wall'
     else
       FFLAGS='-O2 -fallow-argument-mismatch'
       CFLAGS='-O2  -m64 -Wall'
     fi
     if [ $omp ]; then
       echo "OMP settings not available!"
       exit 1
       LIBS='-Wl,-framework -Wl,Accelerate -Wl,-Y -Wl,10'
     else
       LIBS='-Wl,-framework -Wl,Accelerate -Wl,-Y -Wl,10'
     fi
     LFLAGS=' '${LIBS}
     if [ $coverage ]; then
       FFLAGS=${FFLAGS}' --coverage'
       LFLAGS='--coverage '${LFLAGS}
     fi

**Comment by DeepChoudhuri** [comment]
I just want to make a note that I was able to compile CPMD on my apple M1.
